//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctorsforum.Models {
  using System;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;

  public partial class Achievement {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [DisplayName("Achievement ID")]
    public int AchID { get; set; }

    [Required]
    [DisplayName("User ID")]
    [MaxLength(50, ErrorMessage = "User ID is too long")]
    public string User_id { get; set; }

    [Required]
    [DisplayName("Achievement name")]
    [MaxLength(250, ErrorMessage = "Achievement name is too long")]
    public string AchName { get; set; }

    [Required]
    [DisplayName("Issued by")]
    [MaxLength(50, ErrorMessage = "Issued by is too long")]
    public string Issued_by { get; set; }

    [Required]
    [DisplayName("Date range")]
    public System.DateTime Date_Range { get; set; }

    public virtual DB_user DB_user { get; set; }
  }
}
