//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctorsforum.Models {
  using System;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;

  public partial class DB_user {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DB_user() {
      this.Achievements = new HashSet<Achievement>();
      this.Professionals = new HashSet<Professional>();
      this.Qualifications = new HashSet<Qualification>();
    }

    [Key]
    [Required]
    [DisplayName("User ID")]
    [MaxLength(50, ErrorMessage = "User ID is too long")]
    public string User_id { get; set; }

    [Required]
    [DisplayName("Password")]
    [MaxLength(50, ErrorMessage = "Password is too long")]
    public string Password { get; set; }

    [Required]
    [DisplayName("First name")]
    [MaxLength(50, ErrorMessage = "First name is too long")]
    public string First_name { get; set; }

    [Required]
    [DisplayName("Last name")]
    [MaxLength(50, ErrorMessage = "Last name is too long")]
    public string Last_name { get; set; }

    [DisplayName("Image")]
    [MaxLength(250, ErrorMessage = "Image is too long")]
    public string Image { get; set; }

    [Required]
    [DisplayName("Address")]
    [MaxLength(250, ErrorMessage = "Address is too long")]
    public string Address { get; set; }

    [Required]
    [DisplayName("Phone number")]
    [MaxLength(12, ErrorMessage = "Phone number is too long")]
    public string Phone_number { get; set; }

    [Required]
    [DisplayName("Email address")]
    [MaxLength(100, ErrorMessage = "Email address is too long")]
    public string Email_address { get; set; }

    [Required]
    [DisplayName("Sex")]
    [MaxLength(50, ErrorMessage = "Sex is too long")]
    public string Sex { get; set; }

    [Required]
    [DisplayName("Age")]
    [Range(12, 80, ErrorMessage = "Age must be between 12 and 80")]
    public int Age { get; set; }

    [DisplayName("Experience")]
    [MaxLength(50, ErrorMessage = "Experience is too long")]
    public string Experience { get; set; }

    [Required]
    [DisplayName("Profession")]
    [MaxLength(50, ErrorMessage = "Profession is too long")]
    public string profession { get; set; }

    [Required]
    [DisplayName("Public profile")]
    public int public_profile { get; set; }

    [Required]
    [DisplayName("Status")]
    [MaxLength(50, ErrorMessage = "Status is too long")]
    public string Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Achievement> Achievements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Professional> Professionals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Qualification> Qualifications { get; set; }
  }
}
