//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctorsforum.Models {
  using System;
  using System.Collections.Generic;
  using System.ComponentModel;
  using System.ComponentModel.DataAnnotations;
  using System.ComponentModel.DataAnnotations.Schema;

  public partial class Post_Detail {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [DisplayName("Post ID")]
    public int Post_id { get; set; }

    [DisplayName("Post level")]
    public Nullable<int> Level { get; set; }

    [DisplayName("For User")]
    [MaxLength(50, ErrorMessage = "For ID is too long")]
    public string forid { get; set; }

    [DisplayName("Image")]
    [MaxLength(250, ErrorMessage = "Image is too long")]
    public string Image { get; set; }

    [DisplayName("Numerical Order")]
    public int NumericalOrder { get; set; }

    [Required]
    [DisplayName("Topic ID")]
    public int Topic_id { get; set; }

    [DisplayName("Contact email")]
    [MaxLength(100, ErrorMessage = "Contact email is too long")]
    public string Email { get; set; }

    [Required]
    [DisplayName("Posted time")]
    public System.DateTime TimePost { get; set; }

    [Required]
    [DisplayName("Content")]
    public string Content { get; set; }

    [Required]
    [DisplayName("Posted user")]
    [MaxLength(250, ErrorMessage = "Posted user is too long")]
    public string Userpost { get; set; }

    public virtual Topic Topic { get; set; }
  }
}
